//go:build darwin

// pam-agent/internal/register/register_darwin.go
package register

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const bundleName = "PAMAgent.app"

// lsregisterPath is the standard location of the Launch Services registration
// tool on macOS — stable across recent macOS versions.
const lsregisterPath = "/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"

// plistBuddyPath edits the compiled bundle's Info.plist. Ships with the OS
// itself (part of the Property List developer tools), same as lsregister —
// no Xcode Command Line Tools required.
const plistBuddyPath = "/usr/libexec/PlistBuddy"

// Register makes macOS recognize pam-agent:// URLs by building a per-user
// AppleScript applet at ~/Applications/PAMAgent.app that forwards the URL to
// the real agent binary, then force-registering it with lsregister. No admin
// rights required.
//
// WHY AN APPLESCRIPT APPLET AND NOT A BARE BINARY IN THE BUNDLE. This used to
// copy the pam-agent binary itself into Contents/MacOS and make it the
// bundle's CFBundleExecutable — which built and registered without error,
// and then never fired: macOS delivers a registered URL scheme as an Apple
// Event ("open location" / kAEGetURL), not as a command-line argument. A
// bare Mach-O executable with no Apple Event handler installed is launched
// by Launch Services with an EMPTY argument list; the event is sent, nothing
// is listening for it, and the process just runs `pam-agent` with no
// subcommand and exits. Silently — no crash, no log, nothing for the
// operator to see, which is exactly the "doesn't automatically open"
// symptom this fixes. Windows and Linux never had this problem because
// their registration mechanisms (the registry command's "%1", the .desktop
// file's "%u") place the URL directly into argv by convention — there is no
// Windows/Linux equivalent of the Apple Event indirection.
//
// A Script Editor applet (what /usr/bin/osacompile produces) handles
// "open location" out of the box, because AppleScript applets are exactly
// the OS's own supported mechanism for this — see Apple's own
// documentation for `on open location`. It is the only way to receive the
// event without linking Cocoa, and this project builds its macOS binary by
// pure cross-compilation from a non-macOS machine (see
// install/macos/build-pkg.sh) with CGO_ENABLED=0, so an Objective-C/cgo
// Apple Event handler was never an option here: it would need a macOS SDK
// that build never has. Building the applet instead happens here, at
// `pam-agent install` time, ON the operator's own Mac, using tools that
// ship with every macOS install (osacompile, PlistBuddy, lsregister) — no
// build-time dependency changes at all.
func Register(execPath string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("could not determine home directory: %w", err)
	}
	applicationsDir := filepath.Join(home, "Applications")
	bundlePath := filepath.Join(applicationsDir, bundleName)
	resourcesDir := filepath.Join(bundlePath, "Contents", "Resources")
	bundledBinaryPath := filepath.Join(resourcesDir, "pam-agent")

	// ~/Applications does not exist on a stock Mac — nobody creates it until
	// something needs it. osacompile will not create missing grandparent
	// directories for its -o target, so this has to happen before it runs.
	if err := os.MkdirAll(applicationsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create %s: %w", applicationsDir, err)
	}

	// Start from nothing: osacompile writes into a fresh bundle, and a stale
	// bundle from a previous version of this handler (the old bare-binary
	// layout this replaces, or an earlier applet) must not leave orphaned
	// files behind that a straight overwrite wouldn't touch.
	if err := os.RemoveAll(bundlePath); err != nil {
		return fmt.Errorf("failed to remove previous app bundle: %w", err)
	}

	// theURL is substituted here as a literal AppleScript string, not passed
	// at runtime — it is the path to the agent binary bundled inside THIS
	// app, fixed at install time. quoted form of protects the shell command
	// from both that path and the launch URL itself (its token/server query
	// parameters), so neither needs to be shell-metacharacter-safe on its
	// own.
	script := fmt.Sprintf(`-- Auto-generated by "pam-agent install". Do not edit by hand —
-- edits here are lost the next time install runs. See
-- internal/register/register_darwin.go for what this does and why.
on open location theURL
	try
		do shell script quoted form of %q & " launch " & quoted form of theURL
	end try
end open location

on run
	-- Launched with no URL: a Finder double-click, or Launch Services
	-- probing the bundle. Nothing to open.
end run
`, bundledBinaryPath)

	scriptPath := filepath.Join(os.TempDir(), "pam-agent-handler.applescript")
	if err := os.WriteFile(scriptPath, []byte(script), 0o600); err != nil {
		return fmt.Errorf("failed to write AppleScript source: %w", err)
	}
	defer os.Remove(scriptPath)

	if out, err := exec.Command("osacompile", "-o", bundlePath, scriptPath).CombinedOutput(); err != nil {
		return fmt.Errorf("osacompile failed to build the URL-handler app: %w (%s)", err, string(out))
	}

	if err := os.MkdirAll(resourcesDir, 0o755); err != nil {
		return fmt.Errorf("failed to create app bundle resources directory: %w", err)
	}
	if err := copyFile(execPath, bundledBinaryPath); err != nil {
		return fmt.Errorf("failed to copy agent binary into bundle: %w", err)
	}
	if err := os.Chmod(bundledBinaryPath, 0o755); err != nil {
		return fmt.Errorf("failed to make bundled agent binary executable: %w", err)
	}

	// osacompile's own Info.plist has no URL scheme declared — that part of
	// the bundle is still ours to add. CFBundleIdentifier/CFBundleName are
	// set for scalar keys that may or may not already exist depending on
	// the OS version (see setOrAddString); the URL-scheme keys never exist
	// on a fresh osacompile output, so those use Add directly.
	plistPath := filepath.Join(bundlePath, "Contents", "Info.plist")
	if err := setOrAddString(plistPath, ":CFBundleIdentifier", "com.yourorg.pam-agent"); err != nil {
		return err
	}
	if err := setOrAddString(plistPath, ":CFBundleName", "PAM Agent"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :LSUIElement bool true"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :CFBundleURLTypes array"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :CFBundleURLTypes:0 dict"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :CFBundleURLTypes:0:CFBundleURLName string com.yourorg.pam-agent"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :CFBundleURLTypes:0:CFBundleURLSchemes array"); err != nil {
		return err
	}
	if err := plistSet(plistPath, "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string pam-agent"); err != nil {
		return err
	}

	// Force Launch Services to pick up the new/updated bundle immediately,
	// rather than waiting for it to notice on its own schedule.
	if out, err := exec.Command(lsregisterPath, "-f", bundlePath).CombinedOutput(); err != nil {
		return fmt.Errorf("lsregister failed: %w (%s)", err, string(out))
	}
	return nil
}

// plistSet runs one PlistBuddy edit command against path, e.g.
// "Add :LSUIElement bool true". PlistBuddy's own "-c" syntax takes the
// whole command as one string (unlike a normal argv, where each word would
// need its own element), so the caller passes it pre-joined.
func plistSet(path, command string) error {
	out, err := exec.Command(plistBuddyPath, "-c", command, path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("PlistBuddy %q failed: %w (%s)", command, err, string(out))
	}
	return nil
}

// setOrAddString sets a string-valued plist key, trying Set first and
// falling back to Add when the key doesn't exist yet.
//
// This exists because of a confirmed bug on real hardware: an earlier
// version of this file assumed osacompile's own generated Info.plist
// already contains CFBundleIdentifier and CFBundleName (true on some macOS
// versions, apparently not on others — osacompile's default plist contents
// are not documented by Apple), and used a bare "Set" for both. On a Mac
// where the key isn't there, PlistBuddy's Set fails outright with
// "Does Not Exist" rather than creating it — Set only ever changes an
// existing value, it never creates one. That version also had a second,
// independent bug in the same two lines: PlistBuddy's "Set" syntax is
// `Set <entry> <value>` with NO type argument (only "Add" takes a type),
// so "Set :CFBundleIdentifier string com.yourorg.pam-agent" was writing
// the literal value "string com.yourorg.pam-agent" — the word "string"
// included — on any Mac where the Set half had actually succeeded. Both
// are fixed here: Set is now called with just the value, and a failed Set
// falls back to a correctly-typed Add rather than assuming either shape of
// the starting plist.
func setOrAddString(path, keyPath, value string) error {
	setCmd := fmt.Sprintf("Set %s %s", keyPath, value)
	out, err := exec.Command(plistBuddyPath, "-c", setCmd, path).CombinedOutput()
	if err == nil {
		return nil
	}
	if !strings.Contains(string(out), "Does Not Exist") {
		return fmt.Errorf("PlistBuddy %q failed: %w (%s)", setCmd, err, string(out))
	}
	addCmd := fmt.Sprintf("Add %s string %s", keyPath, value)
	if out, err := exec.Command(plistBuddyPath, "-c", addCmd, path).CombinedOutput(); err != nil {
		return fmt.Errorf("PlistBuddy %q failed: %w (%s)", addCmd, err, string(out))
	}
	return nil
}

// Unregister removes the app bundle. macOS's URL-scheme registration itself
// has no simple "unregister" call; removing the bundle it points at is the
// practical equivalent, since Launch Services drops routes to bundles that
// no longer exist.
func Unregister() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	return os.RemoveAll(filepath.Join(home, "Applications", bundleName))
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}
