import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { KeyRound, Eye, EyeOff, Wand2, ShieldCheck, RefreshCw } from 'lucide-react'
import clsx from 'clsx'
import { createCredential, listCredentialTypes } from '../../api/vault'
import { Modal } from '../common/Modal'
import { Field, inputClass, selectClass, FieldSet } from '../common/FormFields'
import { Button } from '../common/Button'
import { apiErrorMessage } from '../../lib/apiError'
import { objectNameRules, passwordStrength, suggestPassword } from '../../lib/validators'

const ROTATION_PRESETS = [0, 30, 60, 90, 180]

const schema = z.object({
  name: z.string().trim().min(2, 'Give this credential a recognisable name').max(120),
  account_name: z
    .string()
    .trim()
    .min(1, 'The account or principal this secret belongs to')
    .max(255)
    .regex(/^[^\s]+(\s[^\s]+)*$/, 'No leading or trailing spaces'),
  credential_type: z.string().min(1, 'Choose what kind of secret this is'),
  secret_plaintext: z.string().min(1, 'The secret itself is required'),
  description: z.string().trim().max(500).optional(),
  folder_id: z.string().optional(),
  rotation_interval_days: z.coerce
    .number({ invalid_type_error: 'Enter a number of days' })
    .int('Whole days only')
    .min(0, 'Use 0 for no schedule')
    .max(3650, 'At most 3650 days'),
})

// Secret-bearing types where a generated value is meaningful. An SSH key or
// a certificate is pasted, never generated by a password generator, so the
// generate affordance only appears where it would actually be correct.
const GENERATABLE = new Set(['password', 'api_key', 'token'])

export function CreateCredentialModal({ open, onClose, safeId, folders = [], folderId }) {
  const queryClient = useQueryClient()
  const [showSecret, setShowSecret] = useState(false)

  const {
    register,
    handleSubmit,
    reset,
    watch,
    setValue,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema),
    mode: 'onBlur',
    defaultValues: {
      name: '',
      account_name: '',
      credential_type: '',
      secret_plaintext: '',
      description: '',
      folder_id: folderId || '',
      rotation_interval_days: 0,
    },
  })

  useEffect(() => {
    if (open) {
      reset({
        name: '',
        account_name: '',
        credential_type: '',
        secret_plaintext: '',
        description: '',
        folder_id: folderId || '',
        rotation_interval_days: 0,
      })
      setShowSecret(false)
    }
  }, [open, folderId, reset])

  // Fetched, not hardcoded: the vault's supported types come from
  // vault_service.go's ListCredentialTypes, so this list can't drift from
  // what the backend will accept.
  const typesQuery = useQuery({
    queryKey: ['vault', 'credential-types'],
    queryFn: ({ signal }) => listCredentialTypes(signal),
    enabled: open,
    staleTime: Infinity,
  })

  const type = watch('credential_type')
  const secret = watch('secret_plaintext') || ''
  const rotation = Number(watch('rotation_interval_days'))
  const strength = passwordStrength(secret)
  const isLongForm = type === 'ssh_key' || type === 'x509_cert' || type === 'kerberos_keytab'

  const mutation = useMutation({
    mutationFn: (values) =>
      createCredential(safeId, {
        ...values,
        folder_id: values.folder_id || undefined,
        description: values.description || undefined,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['vault', 'safes', safeId, 'credentials'] })
      toast.success('Credential stored', {
        description: 'It is encrypted at rest. Revealing it later is recorded against your identity.',
      })
      onClose()
    },
    onError: (err) => toast.error(apiErrorMessage(err)),
  })

  return (
    <Modal
      open={open}
      onClose={onClose}
      icon={KeyRound}
      title="Store a credential"
      description="The secret is encrypted with envelope encryption before it is written. It is never returned in a list response, only through an audited reveal."
      size="xl"
      busy={mutation.isPending}
      footer={
        <>
          <Button variant="ghost" onClick={onClose} disabled={mutation.isPending}>
            Cancel
          </Button>
          <Button
            form="create-credential-form"
            type="submit"
            variant="primary"
            icon={ShieldCheck}
            loading={mutation.isPending}
          >
            Encrypt and store
          </Button>
        </>
      }
    >
      <form
        id="create-credential-form"
        onSubmit={handleSubmit((v) => mutation.mutate(v))}
        noValidate
        className="space-y-6"
      >
        <FieldSet title="What this is">
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Name" error={errors.name?.message} required htmlFor="cred-name">
              <input
                id="cred-name"
                autoComplete="off"
                placeholder="Prod Postgres, app user"
                className={inputClass(!!errors.name)}
                {...register('name', {
                  onChange: (e) => {
                    e.target.value = objectNameRules.sanitize(e.target.value)
                  },
                })}
              />
            </Field>
            <Field
              label="Account name"
              error={errors.account_name?.message}
              hint="The principal the secret authenticates as."
              required
              htmlFor="cred-account"
            >
              <input
                id="cred-account"
                autoComplete="off"
                placeholder="svc_app"
                className={inputClass(!!errors.account_name)}
                {...register('account_name')}
              />
            </Field>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Type" error={errors.credential_type?.message} required htmlFor="cred-type">
              <select
                id="cred-type"
                className={selectClass(!!errors.credential_type)}
                disabled={typesQuery.isLoading}
                {...register('credential_type')}
              >
                <option value="">{typesQuery.isLoading ? 'Loading types…' : 'Select…'}</option>
                {(typesQuery.data || []).map((t) => (
                  <option key={t.type} value={t.type} title={t.description}>
                    {t.label}
                  </option>
                ))}
              </select>
            </Field>
            {folders.length > 0 && (
              <Field label="Folder" hint="Optional, organises the safe's contents." htmlFor="cred-folder">
                <select id="cred-folder" className={selectClass(false)} {...register('folder_id')}>
                  <option value="">Safe root</option>
                  {folders.map((f) => (
                    <option key={f.id} value={f.id}>
                      {f.path || f.name}
                    </option>
                  ))}
                </select>
              </Field>
            )}
          </div>
        </FieldSet>

        <FieldSet title="Secret">
          <Field label="Secret value" error={errors.secret_plaintext?.message} required htmlFor="cred-secret">
            <div className="relative">
              {isLongForm ? (
                <textarea
                  id="cred-secret"
                  rows={5}
                  spellCheck={false}
                  placeholder="-----BEGIN PRIVATE KEY-----"
                  className={clsx(inputClass(!!errors.secret_plaintext), 'font-mono text-xs')}
                  {...register('secret_plaintext')}
                />
              ) : (
                <input
                  id="cred-secret"
                  type={showSecret ? 'text' : 'password'}
                  autoComplete="new-password"
                  spellCheck={false}
                  className={clsx(inputClass(!!errors.secret_plaintext), 'pr-20 font-mono')}
                  {...register('secret_plaintext')}
                />
              )}
              {!isLongForm && (
                <div className="absolute right-1.5 top-1/2 flex -translate-y-1/2 items-center gap-0.5">
                  <button
                    type="button"
                    onClick={() => setShowSecret((v) => !v)}
                    aria-label={showSecret ? 'Hide secret' : 'Show secret'}
                    className="flex h-7 w-7 items-center justify-center rounded-md text-ink-500 transition-colors hover:bg-surface-700 hover:text-ink-100"
                  >
                    {showSecret ? (
                      <EyeOff className="h-3.5 w-3.5" strokeWidth={1.75} />
                    ) : (
                      <Eye className="h-3.5 w-3.5" strokeWidth={1.75} />
                    )}
                  </button>
                  {GENERATABLE.has(type) && (
                    <button
                      type="button"
                      onClick={() => {
                        setValue('secret_plaintext', suggestPassword(24), { shouldValidate: true })
                        setShowSecret(true)
                      }}
                      title="Generate a strong value"
                      aria-label="Generate a strong value"
                      className="flex h-7 w-7 items-center justify-center rounded-md text-ink-500 transition-colors hover:bg-surface-700 hover:text-ink-100"
                    >
                      <Wand2 className="h-3.5 w-3.5" strokeWidth={1.75} />
                    </button>
                  )}
                </div>
              )}
            </div>
          </Field>

          {/* Advisory only, never blocks a submit the server would accept. */}
          {!isLongForm && secret && (
            <div className="flex items-center gap-3">
              <div className="flex h-1.5 flex-1 gap-1 overflow-hidden rounded-full">
                {[1, 2, 3, 4, 5].map((i) => (
                  <span
                    key={i}
                    className={clsx(
                      'h-full flex-1 rounded-full transition-colors duration-200',
                      i <= strength.score
                        ? strength.tone === 'red'
                          ? 'bg-red-500'
                          : strength.tone === 'amber'
                            ? 'bg-amber-500'
                            : 'bg-emerald-500'
                        : 'bg-surface-750'
                    )}
                  />
                ))}
              </div>
              <span
                className={clsx(
                  'flex-none text-2xs font-medium',
                  strength.tone === 'red'
                    ? 'text-red-600 dark:text-red-400'
                    : strength.tone === 'amber'
                      ? 'text-amber-600 dark:text-amber-400'
                      : 'text-emerald-600 dark:text-emerald-400'
                )}
              >
                {strength.label}
              </span>
            </div>
          )}

          <Field label="Description" hint="Optional, what this credential is for." htmlFor="cred-description">
            <input id="cred-description" className={inputClass(false)} {...register('description')} />
          </Field>
        </FieldSet>

        <FieldSet
          title="Rotation"
          description="A schedule the vault uses to flag this credential for rotation. Rotation itself is still requested explicitly from the credential's page."
        >
          <div className="flex flex-wrap items-center gap-2">
            {ROTATION_PRESETS.map((d) => {
              const active = rotation === d
              return (
                <button
                  key={d}
                  type="button"
                  onClick={() => setValue('rotation_interval_days', d, { shouldValidate: true })}
                  aria-pressed={active}
                  className={clsx(
                    'inline-flex h-8 items-center gap-1.5 rounded-lg border px-3 text-xs font-medium transition-colors',
                    active
                      ? 'border-blue-500/50 bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-200'
                      : 'border-surface-700 bg-surface-900 text-ink-300 hover:border-surface-600'
                  )}
                >
                  {d === 0 ? <RefreshCw className="h-3 w-3" strokeWidth={2} /> : null}
                  {d === 0 ? 'No schedule' : `${d} days`}
                </button>
              )
            })}
            <div className="w-24">
              <input
                inputMode="numeric"
                aria-label="Custom rotation interval in days"
                className={clsx(inputClass(!!errors.rotation_interval_days), 'h-9 py-0 text-center text-sm')}
                {...register('rotation_interval_days', {
                  onChange: (e) => {
                    e.target.value = e.target.value.replace(/[^0-9]/g, '').slice(0, 4)
                  },
                })}
              />
            </div>
          </div>
          {errors.rotation_interval_days && (
            <p className="text-xs font-medium text-red-600 dark:text-red-400">
              {errors.rotation_interval_days.message}
            </p>
          )}
        </FieldSet>
      </form>
    </Modal>
  )
}
